language: emacs-lisp

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw | sh
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - sudo apt-get update

install:
  - sudo apt-get install emacs 

script:
  - emacs --version
  - cask install
  - make test

notifications:
  email: false